FROM scratch
MAINTAINER Jeff Chan <pm751211@gmail.com>
COPY libcap.so.2 /lib/x86_64-linux-gnu/libcap.so.2
COPY libc.so.6 /lib/x86_64-linux-gnu/libc.so.6
COPY ld-linux-x86-64.so.2 /lib64/ld-linux-x86-64.so.2
COPY ping /bin/ping
